/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    FollowMe: typeof import('./../src/components/Studio/components/follow-me.vue')['default']
    Gift: typeof import('./../src/components/opfans/Gift.vue')['default']
    GiftCard: typeof import('./../src/components/gift-card/index.vue')['default']
    Imgbox: typeof import('./../src/components/Imgbox/index.vue')['default']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutVideo: typeof import('@nutui/nutui')['Video']
    Openfansbox: typeof import('./../src/components/Imgbox/openfansbox.vue')['default']
    Opfans: typeof import('./../src/components/opfans/index.vue')['default']
    PrivateMact: typeof import('./../src/components/private-mact/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./../src/components/share/index.vue')['default']
    Studio: typeof import('./../src/components/Studio/index.vue')['default']
    StudioBottom: typeof import('./../src/components/Studio/components/studio-bottom.vue')['default']
    StudioChat: typeof import('./../src/components/Studio/components/studio-chat.vue')['default']
    StudioHead: typeof import('./../src/components/Studio/components/studio-head.vue')['default']
    StudioVideo: typeof import('./../src/components/Studio/components/studio-video.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
